import { useState } from 'react';
import { Download, ExternalLink } from 'lucide-react';
import { saveAs } from 'file-saver';
import * as XLSX from 'xlsx';
import { DiseaseModal } from './DiseaseModal';
import { Modal } from './Modal';

interface Props { headers:string[]; rows:unknown[][]; caption?:string; }
export function DataTable({headers,rows,caption}:Props){
  const [all,setAll]=useState(false);const [disease,setDisease]=useState<string|null>(null);const [gene,setGene]=useState<{id:string;name:string}|null>(null);const displayed=all?rows:rows.slice(0,10);const ensemblIndex=headers.findIndex(h=>/ensembl/i.test(h));const geneIndex=headers.findIndex(h=>/gene symbol|^gene$/i.test(h));
  const exportExcel=()=>{const ws=XLSX.utils.aoa_to_sheet([headers,...rows]);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Results');const buf=XLSX.write(wb,{bookType:'xlsx',type:'array'});saveAs(new Blob([buf],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),'chatalchemy-results.xlsx')};
  const render=(cell:unknown,row:unknown[],idx:number)=>{const value=String(cell??'');if(idx===geneIndex&&ensemblIndex>=0){const id=String(row[ensemblIndex]??'');return <button className="font-medium text-blue-600 hover:underline dark:text-blue-400" onClick={()=>id&&setGene({id,name:value})}>{value.toUpperCase()}</button>}const efo=value.match(/\b(EFO_\d+|MONDO_\d+|OTAR_\w+)\b/);if(efo)return <span>{value.split(efo[0])[0]} <button className="text-purple-600 hover:underline dark:text-purple-400" onClick={()=>setDisease(efo[0])}>[{efo[0]}]</button></span>;if(/^ENSG\d+$/i.test(value))return <a className="inline-flex items-center gap-1 text-purple-600 hover:underline dark:text-purple-400" href={`https://ensembl.org/Homo_sapiens/Gene/Summary?g=${encodeURIComponent(value)}`} target="_blank" rel="noreferrer">{value}<ExternalLink className="h-3 w-3"/></a>;return value};
  return <><div className="overflow-x-auto rounded-xl border border-gray-100 bg-white p-4 dark:border-gray-700 dark:bg-gray-800"><div className="mb-3 flex items-center justify-between"><h3 className="font-semibold text-gray-900 dark:text-gray-100">{caption||'Results'}</h3><button onClick={exportExcel} title="Export to Excel" className="p-2 text-gray-500 hover:text-purple-600"><Download className="h-5 w-5"/></button></div><table className="min-w-full text-sm"><thead><tr className="border-b dark:border-gray-700">{headers.map(h=><th key={h} className="whitespace-nowrap p-3 text-left text-xs font-medium uppercase tracking-wide text-gray-500">{h}</th>)}</tr></thead><tbody>{displayed.map((row,ri)=><tr key={ri} className="border-b last:border-0 hover:bg-gray-50 dark:border-gray-700 dark:hover:bg-gray-700/40">{row.map((c,ci)=><td key={ci} className="max-w-[420px] p-3 align-top text-gray-700 dark:text-gray-300">{render(c,row,ci)}</td>)}</tr>)}</tbody></table>{rows.length>10&&<div className="mt-3 text-center"><button onClick={()=>setAll(!all)} className="text-sm text-purple-600 hover:underline dark:text-purple-400">{all?'Show Less':`Show All (${rows.length} rows)`}</button></div>}</div><DiseaseModal isOpen={!!disease} onClose={()=>setDisease(null)} efoId={disease||''}/><Modal isOpen={!!gene} onClose={()=>setGene(null)} ensemblId={gene?.id} geneName={gene?.name}/></>;
}
