import { useEffect, useMemo, useState } from 'react';
import { Dna, MessageSquare, PanelLeftClose, PanelLeftOpen, Plus } from 'lucide-react';
import type { Chat, Message, QueryResponse } from './types';
import { ChatHeader } from './components/ChatHeader';
import { ChatInput } from './components/ChatInput';
import { ChatMessage } from './components/ChatMessage';
import { BiomedicalModule } from './components/biomedical/BiomedicalModule';
import { chat as chatApi, queryLive } from './lib/api';
import { clearData, getCandidateDrugEvidence, getLoadedFiles, loadBackendData, searchKnowledgeBase } from './lib/knowledge';
import { createNewChat, deleteChat, generateChatName, getAllChats, getChatById, saveChat } from './lib/storage';

const LIVE_TERMS = /\b(fda|dailymed|clinical\s*trials?|trial|rxnorm|rxcui|chembl|pubchem|open\s*targets?|targeting|approved|approval|smiles|iupac)\b/i;
const newId = () => crypto.randomUUID();
function responseMessage(data: QueryResponse): Message {
  const seen = new Set<string>();
  return { id: newId(), role: 'assistant', content: data.answer, timestamp: new Date(), supportRate: data.supported_claim_rate, warnings: data.warnings, tableData: data.table || undefined, chartData: data.chart || undefined, provenance: (data.evidence || []).filter(e => { const k = `${e.source}:${e.source_record_id || e.id}`; if (seen.has(k)) return false; seen.add(k); return true; }).map(e => ({ id: e.id, source: e.source, recordId: e.source_record_id, url: e.source_url })) };
}
export default function App() {
  const [currentChat, setCurrentChat] = useState<Chat | null>(null); const [isLoading, setLoading] = useState(false); const [loadedFiles, setLoadedFiles] = useState<string[]>([]); const [error, setError] = useState<string | null>(null); const [showBiomedical, setShowBiomedical] = useState(false); const [showChat, setShowChat] = useState(false); const [darkMode, setDarkMode] = useState(() => localStorage.getItem('theme') === 'dark' || (!localStorage.getItem('theme') && matchMedia('(prefers-color-scheme: dark)').matches));
  useEffect(() => { document.documentElement.classList.toggle('dark', darkMode); localStorage.setItem('theme', darkMode ? 'dark' : 'light'); }, [darkMode]);
  useEffect(() => { void loadBackendData().then(() => setLoadedFiles(getLoadedFiles())).catch(() => setError('Could not restore previously uploaded data.')); }, []);
  const chats = useMemo(() => getAllChats(), [currentChat?.updatedAt, showChat, showBiomedical]);
  const newChat = () => { const c = createNewChat(); c.messages = [{ id: newId(), role: 'assistant', content: 'Welcome to **ChatAlchemy**. Ask about your uploaded data, live pharmaceutical databases, clinical trials, genes, diseases, compounds, or continue an analysis from the Biomedical workspace.', timestamp: new Date() }]; saveChat(c); setCurrentChat({ ...c }); setShowBiomedical(false); setShowChat(true); setError(null); };
  const selectChat = (id: string) => { const c = getChatById(id); if (c) { setCurrentChat({ ...c }); setShowChat(true); setShowBiomedical(false); setError(null); } };
  const removeChat = (id: string) => { deleteChat(id); if (currentChat?.id === id) { setCurrentChat(null); setShowChat(false); } };
  const renameCurrent = (id: string, name: string) => { if (currentChat?.id === id) setCurrentChat({ ...currentChat, name, updatedAt: new Date() }); };
  const fileUploaded = () => { setLoadedFiles(getLoadedFiles()); setError(null); if (currentChat) { const m: Message = { id: newId(), role: 'assistant', content: 'Uploaded data is ready. I can filter, count, tabulate, chart, or combine candidate drug names with live evidence.', timestamp: new Date() }; const c = { ...currentChat, messages: [...currentChat.messages, m], updatedAt: new Date() }; setCurrentChat(c); saveChat(c); } };
  const clearUploaded = () => { void clearData().then(() => setLoadedFiles([])); if (currentChat) { const m: Message = { id: newId(), role: 'assistant', content: 'Uploaded data has been cleared. Live biomedical sources remain available.', timestamp: new Date() }; const c = { ...currentChat, messages: [...currentChat.messages, m], updatedAt: new Date() }; setCurrentChat(c); saveChat(c); } };
  const send = async (content: string) => {
    if (!currentChat) return; const user: Message = { id: newId(), role: 'user', content, timestamp: new Date() }; let c: Chat = { ...currentChat, messages: [...currentChat.messages, user], updatedAt: new Date() }; if (currentChat.messages.length === 1) c = { ...c, name: await generateChatName(content) }; setCurrentChat(c); saveChat(c); setLoading(true); setError(null);
    try {
      const uploaded = await searchKnowledgeBase(content); const isDataOutput = !!(uploaded.tableData || uploaded.chartData) && !LIVE_TERMS.test(content); let assistant: Message;
      if (isDataOutput) assistant = { id: newId(), role: 'assistant', content: `I found **${uploaded.matchCount} matching record${uploaded.matchCount === 1 ? '' : 's'}** in your uploaded data.`, timestamp: new Date(), tableData: uploaded.tableData, chartData: uploaded.chartData };
      else { const conversation = c.messages.slice(-10).map(m => ({ role: m.role, content: m.content })); let data: QueryResponse; if (LIVE_TERMS.test(content)) { const candidates = await getCandidateDrugEvidence(); data = await queryLive(content, conversation, candidates); } else data = await chatApi(conversation, uploaded.text || undefined); assistant = responseMessage(data); if (uploaded.matchCount > 0 && !assistant.tableData && !assistant.chartData && !LIVE_TERMS.test(content)) assistant.content += `\n\nI also matched **${uploaded.matchCount} record(s)** in your uploaded data for this question.`; }
      c = { ...c, messages: [...c.messages, assistant], updatedAt: new Date() }; setCurrentChat(c); saveChat(c);
    } catch (e) { const msg = e instanceof Error ? e.message : 'Unknown request error'; setError(msg); const assistant: Message = { id: newId(), role: 'assistant', content: 'I could not complete that request. I did not substitute an unsupported biomedical answer.', timestamp: new Date(), warnings: [msg] }; c = { ...c, messages: [...c.messages, assistant], updatedAt: new Date() }; setCurrentChat(c); saveChat(c); } finally { setLoading(false); }
  };
  const transfer = () => { const latest = getAllChats()[0]; if (latest) { setCurrentChat({ ...latest }); setShowChat(true); } };
  const home = () => { setCurrentChat(null); setShowBiomedical(false); setShowChat(false); setError(null); };
  const toggleBiomedical = () => { if (showBiomedical) { setShowBiomedical(false); setShowChat(true); if (!currentChat) { const first = getAllChats()[0]; if (first) setCurrentChat({ ...first }); else newChat(); } } else { setShowBiomedical(true); setShowChat(false); } };
  const chatView = () => <div className="flex min-w-0 flex-1 flex-col overflow-hidden">{error && <div className="mx-auto mt-2 w-[95%] rounded-lg bg-red-50 p-2 text-sm text-red-600 dark:bg-red-950/30 dark:text-red-300">{error}</div>}<div className="flex-1 overflow-y-auto bg-gradient-to-b from-purple-50 to-white dark:from-gray-900 dark:to-gray-800"><div className="mx-auto max-w-[95%]">{currentChat?.messages.map(m => <ChatMessage key={m.id} message={m} darkMode={darkMode} />)}{isLoading && <div className="flex gap-2 p-5"><span className="h-2 w-2 animate-bounce rounded-full bg-purple-600" /><span className="h-2 w-2 animate-bounce rounded-full bg-purple-600 [animation-delay:-.2s]" /><span className="h-2 w-2 animate-bounce rounded-full bg-purple-600 [animation-delay:-.4s]" /><span className="ml-2 text-xs text-gray-500">Querying evidence…</span></div>}</div></div><ChatInput onSend={send} disabled={isLoading} darkMode={darkMode} /></div>;
  const landing = () => <div className="flex h-[calc(100vh-4rem)] items-center justify-center bg-gradient-to-b from-purple-50 to-white p-4 dark:from-gray-900 dark:to-gray-800"><div className="w-full max-w-3xl space-y-8"><div className="text-center"><h1 className="mb-3 text-4xl font-bold text-gray-900 dark:text-white">Welcome to ChatAlchemy</h1><p className="text-lg text-gray-600 dark:text-gray-300">Live biomedical evidence, user data analysis, and research-paper exploration in one workspace.</p></div><div className="grid gap-6 md:grid-cols-2"><button onClick={newChat} className="rounded-xl border-2 border-purple-200 bg-white p-6 text-left transition hover:-translate-y-1 hover:border-purple-500 dark:border-purple-800 dark:bg-gray-800"><div className="mb-3 flex items-center gap-3"><Plus className="h-6 w-6 text-purple-600" /><h2 className="text-xl font-semibold dark:text-white">ChatAlchemy</h2></div><p className="text-sm text-gray-600 dark:text-gray-400">Chat with uploaded data and live RxNorm, DailyMed, FDA, trial, ChEMBL, Open Targets, and PubChem evidence.</p></button><button onClick={() => { setShowBiomedical(true); setShowChat(false); setCurrentChat(null); }} className="rounded-xl border-2 border-purple-200 bg-white p-6 text-left transition hover:-translate-y-1 hover:border-purple-500 dark:border-purple-800 dark:bg-gray-800"><div className="mb-3 flex items-center gap-3"><Dna className="h-6 w-6 text-purple-600" /><h2 className="text-xl font-semibold dark:text-white">Biomedical Analysis</h2></div><p className="text-sm text-gray-600 dark:text-gray-400">Analyze PDF/TXT papers, genes, diseases, enrichment, and live evidence networks.</p></button></div>{chats.length > 0 && <div className="rounded-xl bg-white p-6 dark:bg-gray-800"><h2 className="mb-3 flex items-center gap-2 text-xl font-semibold dark:text-white"><MessageSquare className="h-5 w-5 text-purple-600" />Recent Conversations</h2><div className="max-h-64 overflow-y-auto">{chats.slice(0, 8).map(c => <button key={c.id} onClick={() => selectChat(c.id)} className="flex w-full items-center justify-between rounded-lg p-3 text-left hover:bg-gray-50 dark:hover:bg-gray-700"><span className="font-medium text-gray-700 dark:text-gray-200">{c.name}</span><span className="text-xs text-gray-500">{c.updatedAt.toLocaleDateString()}</span></button>)}</div></div>}</div></div>;
  return <div className={`flex h-screen flex-col ${darkMode ? 'dark' : ''}`}><ChatHeader chatName={currentChat?.name || (showBiomedical ? 'Biomedical Analysis' : 'ChatAlchemy')} chatId={currentChat?.id || null} loadedFiles={loadedFiles} onClearData={clearUploaded} onFileUpload={() => fileUploaded()} onUploadError={setError} onSelectChat={selectChat} onNewChat={newChat} onDeleteChat={removeChat} darkMode={darkMode} toggleTheme={() => setDarkMode(v => !v)} onToggleBiomedical={toggleBiomedical} showBiomedical={showBiomedical} onGoHome={home} onRenameChat={renameCurrent} />{currentChat || showBiomedical ? <div className="relative flex flex-1 overflow-hidden">{showBiomedical && <div className={`${showChat ? 'w-1/2' : 'w-full'} overflow-y-auto`}><BiomedicalModule onTransferToChat={transfer} /></div>}{currentChat && showChat && <div className={`${showBiomedical ? 'w-1/2' : 'w-full'} flex overflow-hidden border-l dark:border-gray-700`}>{chatView()}</div>}{currentChat && showBiomedical && <button onClick={() => setShowChat(v => !v)} title={showChat ? 'Close chat' : 'Open chat'} className={`fixed top-20 z-30 rounded-full p-2 shadow-lg ${showChat ? 'right-[calc(50%-1.5rem)]' : 'right-4'} bg-white text-gray-600 dark:bg-gray-800 dark:text-gray-300`}>{showChat ? <PanelLeftClose className="h-5 w-5" /> : <PanelLeftOpen className="h-5 w-5" />}</button>}</div> : landing()}</div>;
}
