import { useState } from 'react';
import { Share, BookOpen, Brain, Network, FlaskConical } from 'lucide-react';
import { createNewChat, saveChat } from '../../lib/storage';
import { DataTable } from '../DataTable';
interface Results { genes?: string[]; explanation: string; paperSummary?: string; tableData?: { headers: string[]; rows: unknown[][]; caption?: string }; clusters?: Array<{ id: number; genes: string[]; description?: string }>; enrichmentResults?: Array<{ term: string; genes: string[]; pValue: number; adjustedPValue: number }>; evidence?: Array<{ source: string; source_record_id?: string }>; }
function suggestions(results: Results): string[] { const genes = (results.genes || []).slice(0, 4).join(', '); return [genes ? `What FDA-approved drugs target ${genes}?` : 'What approved drugs are relevant to these findings?', 'Which findings have recruiting Phase 3 clinical trials?', 'How do the live database results compare with the uploaded paper?']; }
export function ResultsViewer({ results, onTransferToChat }: { results: Results; onTransferToChat?: () => void }) {
  const [moving, setMoving] = useState(false);
  const transfer = () => { setMoving(true); try { const chat = createNewChat('Biomedical Analysis'); const context = `# Biomedical Analysis Context\n\n${results.paperSummary ? `## Literature Summary\n${results.paperSummary}\n\n` : ''}## Live Evidence Analysis\n${results.explanation}\n\n## Genes\n${(results.genes || []).join(', ') || 'None'}\n\n## Enrichment\n${(results.enrichmentResults || []).slice(0, 10).map(x => `- ${x.term}: q=${x.adjustedPValue.toExponential(2)}; genes=${x.genes.join(', ')}`).join('\n') || 'No enrichment terms'}\n\nThis context came from the Biomedical Analysis workspace and live Open Targets evidence.`; chat.analysisContext = { genes: results.genes || [], paperSummary: results.paperSummary || '', enrichment: results.enrichmentResults || [] }; chat.messages = [{ id: crypto.randomUUID(), role: 'assistant', content: context, timestamp: new Date() }, { id: crypto.randomUUID(), role: 'assistant', content: `Suggested follow-up questions:\n\n${suggestions(results).map((q, i) => `[Q${i + 1}] ${q}`).join('\n\n')}`, timestamp: new Date() }]; saveChat(chat); onTransferToChat?.(); } finally { setMoving(false); } };
  return <div className="space-y-6"><div className="flex justify-end"><button onClick={transfer} disabled={moving} className="inline-flex items-center gap-2 rounded-lg bg-purple-600 px-4 py-2 text-white hover:bg-purple-700 disabled:opacity-50"><Share className="h-4 w-4" />{moving ? 'Transferring…' : 'Continue in Chat'}</button></div>{results.tableData && <DataTable {...results.tableData} />}<section className="rounded-xl border bg-white p-6 dark:border-gray-700 dark:bg-gray-800"><h3 className="mb-3 flex items-center gap-2 text-lg font-semibold dark:text-white"><BookOpen className="h-5 w-5 text-purple-600" />Literature Summary</h3><p className="whitespace-pre-line text-gray-700 dark:text-gray-300">{results.paperSummary || 'No uploaded-paper summary is active for this analysis.'}</p></section><section className="rounded-xl border bg-white p-6 dark:border-gray-700 dark:bg-gray-800"><h3 className="mb-3 flex items-center gap-2 text-lg font-semibold dark:text-white"><Brain className="h-5 w-5 text-purple-600" />Analysis Insights</h3><p className="text-gray-700 dark:text-gray-300">{results.explanation}</p></section>{!!results.clusters?.length && <section className="rounded-xl border bg-white p-6 dark:border-gray-700 dark:bg-gray-800"><h3 className="mb-3 flex items-center gap-2 text-lg font-semibold dark:text-white"><Network className="h-5 w-5 text-purple-600" />Gene Clusters</h3><div className="grid gap-3 md:grid-cols-2">{results.clusters.map(c => <div key={c.id} className="rounded-lg bg-gray-50 p-4 dark:bg-gray-700/50"><div className="mb-2 font-medium dark:text-white">Cluster {c.id}</div><div className="flex flex-wrap gap-2">{c.genes.map(g => <span key={g} className="rounded-full bg-purple-100 px-3 py-1 text-sm text-purple-800 dark:bg-purple-900/50 dark:text-purple-200">{g}</span>)}</div><p className="mt-2 text-xs text-gray-500">{c.description}</p></div>)}</div></section>}{!!results.enrichmentResults?.length && <section className="rounded-xl border bg-white p-6 dark:border-gray-700 dark:bg-gray-800"><h3 className="mb-3 flex items-center gap-2 text-lg font-semibold dark:text-white"><FlaskConical className="h-5 w-5 text-purple-600" />Disease-set Enrichment</h3><div className="space-y-2">{results.enrichmentResults.slice(0, 15).map(r => <div key={r.term} className="flex flex-col justify-between rounded-lg bg-gray-50 p-3 text-sm dark:bg-gray-700/50 md:flex-row"><span className="font-medium dark:text-white">{r.term}</span><span className="text-gray-500 dark:text-gray-300">q={r.adjustedPValue.toExponential(2)} · {r.genes.join(', ')}</span></div>)}</div></section>}</div>;
}
